// <auto-generated />
namespace Eskaney.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pic111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pic111));
        
        string IMigrationMetadata.Id
        {
            get { return "202010091301535_pic111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
